### ISSUE TITLE
Started getting error: Array index is out of range.

### ISSUE THREAD

**Issue by ghost** [googlevr/daydream-renderer-for-unity#1]
Dell XPS 2720, Windows 10 (14393.1198), GeForce GT 750M
Unity 2017.1.0f3
GVR Unity SDK 1.60
Daydream Renderer 1.0
Controller Emulator 1.5.01

I have 4 lights (Bottom, Top, Side1, Side2), but the renderer tries to access a fifth light.
Mostly this works fine w/o any errors, but in one condition (can reproduce) I get this error.
It is always the same game object in my UI that the error occurs on.

Any direction to help resolve the issue is much appreciated.

Renderer setup and mesh-material setup:
![renderer_setup](https://user-images.githubusercontent.com/23744336/28503542-32c15964-6fd7-11e7-801a-dfcf5c5d9be3.jpg)

![mesh_setup](https://user-images.githubusercontent.com/23744336/28503557-99481f1a-6fd7-11e7-8ef7-b807f1091b33.jpg)

I get this error with this stack trace:
```
IndexOutOfRangeException: Array index is out of range.
daydreamrenderer.DaydreamMeshRenderer.ApplyLighting (Boolean lightChange) (at Assets/DaydreamRenderer/Scripts/DaydreamMeshRenderer.cs:374)
daydreamrenderer.DaydreamLightingManager.ProcessLighting (UnityEngine.Camera camera) (at Assets/DaydreamRenderer/Scripts/DaydreamLightingManager.cs:176)
UnityEngine.Camera.FireOnPreRender (UnityEngine.Camera cam) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/CameraBindings.gen.cs:739)
```

The code where the error happens is the last line here, I added some debug lines:
```
                if (lightIdx != -1 && (!m_static || m_daydreamLightArray[lightIdx].m_curMode == LightModes.REALTIME))
                {
                    noLights = false;

                    if (lightIdx < 0 || lightIdx >= m_daydreamLightArray.Length)
                    {
                        DebugX.Log("Out of range: " + transform.parent.parent.gameObject.name + "::" + transform.parent.gameObject.name + "::" + gameObject.name + " i=" + i + " idx=" + lightIdx + " len=" + m_daydreamLightArray.Length + " act=" + m_activeLightCount);
                        for (int j = 0; j < m_activeLightCount; ++j)
                        {
                            int index = m_lightList[j];
                            string name = "";
                            if (index >= 0 && index < m_daydreamLightArray.Length)
                            {
                                name = m_daydreamLightArray[index].GetComponent<Light>().name;
                            }
                            DebugX.Log("Out of range: j=" + j + " idx=" + index + " name=" + name);
                        }
                    }
                    DaydreamLight dl = m_daydreamLightArray[lightIdx];
```
Debug output:
```
18:21:47.770:I:840: Out of range: i=4 idx=4 len=4 act=8
18:21:47.773:I:840: Out of range: j=0 idx=0 name=Bottom
18:21:47.775:I:840: Out of range: j=1 idx=1 name=Top
18:21:47.777:I:840: Out of range: j=2 idx=2 name=Side2
18:21:47.780:I:840: Out of range: j=3 idx=3 name=Side1
18:21:47.782:I:840: Out of range: j=4 idx=4 name=
18:21:47.785:I:840: Out of range: j=5 idx=-1 name=
18:21:47.787:I:840: Out of range: j=6 idx=-1 name=
18:21:47.790:I:840: Out of range: j=7 idx=-1 name=
```

**Comment by ghost** [comment]
Hi thanks for posting! Nothing about the setup looks unusual, you said that you are able to reproduce, if you list the steps I will try it out.

**Comment by ghost** [comment]
Update: turns out I had 6 lights not 4 total, and had 2 of the lights in a hierarchy group that was SetActive(false) just before this occurred. I will try to replicate just that to see, but maybe the light was still included even though it was inactive (via SetActive(false) rather than light.enabled=false).

Will get back to you in a day or so, thanks.

**Comment by ghost** [comment]
Cool, deactivating the light is a test case, I will play around with that scenario as well to see if there is a regression.

**Comment by ghost** [comment]
OK, I tried to create a new project with the same config, but it worked fine. Also tried to checkout a previous commit on github, but that worked also, so I am not sure now, maybe a freak sequence of events got either Unity or DR into an odd state. I"ll try some more ideas, but I think I may not be able to reproduce it again.

**Comment by nathanmartz** [comment]
Closing for now, then. Please re-open if you're able to repro.
