### ISSUE TITLE
Do Daydream Renderer shaders have variants and need to be in the scene to be available  via code?

### ISSUE THREAD

**Issue by ghost** [googlevr/daydream-renderer-for-unity#2]
Unity shaders have variants (details [here](https://docs.unity3d.com/Manual/MaterialsAccessingViaScript.html)) so that materials modified by scripts at runtime need to be in the scene so that all shader variants that may be needed are loaded.

Do the Daydream Renderer shaders have the same requirement?

My app does a lot of runtime material changes.

**Comment by jchernobieff** [comment]
Daydream Renderer materials have several options and it would be inefficient to select these options using runtime conditionals. In addition shader variants are used to render shadow maps, since many different vertex input/output formats are needed.

So, yes, DDR shaders have many variants.
